development: &defaults
  client_id: 289362154416578
  client_secret: d15884b9322eef11247f60cefdba7c4f
  scope: publish_stream
  canvas_url: http://foda-se.heroku.com/

test:
  <<: *defaults

production:
  <<: *defaults
