development: &defaults
  client_id: ENV['CLIENT_ID']
  client_secret: ENV['CLIENT_SECRET']
  scope: user_about_me,email,publish_stream
  canvas_url: http://foda-se.heroku.com/

test:
  <<: *defaults

production:
  <<: *defaults
