development: &defaults
  client_id: 289362154416578
  client_secret: 27f9eb22806a5a92324768c0c3b74705
  scope: user_about_me,email,publish_stream
  canvas_url: http://localhost:3000/

test:
  <<: *defaults

production:
  <<: *defaults
